show_on:
  default: all
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - below-site-header

background_image:
  type: upload
  default: ""
  description: background image for the banner

clickable_image:
  type: upload
  default: ""
  description: image with a link

tile_background_image: false

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out
